package com.landg.phoenix.paymentraise.common.constants;

/**
 *
 * Payment raise batch SQL constants
 *
 */

public class SQLConstants {
	private SQLConstants() {
	}

	public static final int PAGE_SIZE = 500;

	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART1 = "SELECT COUNT(*) FROM PHOENIX_PREMIUM.PREMIUM_COMPONENT ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART2 = "WHERE (NEXT_PREM_DUE_DATE >= ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART3 = " AND NEXT_PREM_DUE_DATE <= ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART4 = ") AND (NEXT_PREM_DUE_DATE >= EFF_START_DATE AND NEXT_PREM_DUE_DATE <= EFF_END_DATE) ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART5 = " AND (STATUS IN ('01', '04', '05')) ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE_PART6 = " AND POLICY IS NOT NULL ";

	public static final String PREMIUM_COMPONENT_SELECT_DISTINCT_COUNT_CLAUSE = "SELECT DISTINCT(COUNT(*) OVER ()) FROM PHOENIX_PREMIUM.PREMIUM_COMPONENT ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART1 = "WHERE LAST_PAYMENT_UID IS NOT NULL";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART2 = " AND (NEXT_PREM_DUE_DATE >= ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART3 = " AND NEXT_PREM_DUE_DATE <= ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART4 = ") AND (NEXT_PREM_DUE_DATE >= EFF_START_DATE AND NEXT_PREM_DUE_DATE <= EFF_END_DATE) ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART5 = " AND (STATUS IN ('01', '04', '05')) ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_WHERE_CLAUSE_PART6 = " AND POLICY IS NOT NULL ";
	public static final String PREMIUM_COMPONENT_SELECT_COUNT_GROUP_BY_CLAUSE = "GROUP BY EFF_START_DATE, POLICY, COLLECTN_DAY, BANK_DETAIL_UID, STATUS, LAST_PAYMENT_UID, NEXT_PREM_DUE_DATE, NEXT_PAYT_DUE_DATE, PREM_FREQUENCY ";

	public static final String PREMIUM_COMPONENT_SELECT_DISTINCT_MIN_CLAUSE = "SELECT DISTINCT(MIN(LAST_PAYMENT_UID) OVER()) FROM PHOENIX_PREMIUM.PREMIUM_COMPONENT ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART1 = "WHERE LAST_PAYMENT_UID IS NOT NULL";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART2 = " AND (NEXT_PREM_DUE_DATE >= ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART3 = " AND NEXT_PREM_DUE_DATE <= ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART4 = ") AND (NEXT_PREM_DUE_DATE >= EFF_START_DATE AND NEXT_PREM_DUE_DATE <= EFF_END_DATE) ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART5 = " AND (STATUS IN ('01', '04', '05')) ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_WHERE_CLAUSE_PART6 = " AND POLICY IS NOT NULL ";
	public static final String PREMIUM_COMPONENT_SELECT_MIN_GROUP_BY_CLAUSE = "GROUP BY EFF_START_DATE, POLICY, COLLECTN_DAY, BANK_DETAIL_UID, STATUS, LAST_PAYMENT_UID, NEXT_PREM_DUE_DATE, NEXT_PAYT_DUE_DATE, PREM_FREQUENCY ";

	public static final String PREMIUM_COMPONENT_SELECT_DISTINCT_MAX_CLAUSE = "SELECT DISTINCT(MAX(LAST_PAYMENT_UID) OVER()) FROM PHOENIX_PREMIUM.PREMIUM_COMPONENT ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART1 = "WHERE LAST_PAYMENT_UID IS NOT NULL";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART2 = " AND (NEXT_PREM_DUE_DATE >= ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART3 = " AND NEXT_PREM_DUE_DATE <= ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART4 = ") AND (NEXT_PREM_DUE_DATE >= EFF_START_DATE AND NEXT_PREM_DUE_DATE <= EFF_END_DATE) ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART5 = " AND (STATUS IN ('01', '04', '05')) ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_WHERE_CLAUSE_PART6 = " AND POLICY IS NOT NULL ";
	public static final String PREMIUM_COMPONENT_SELECT_MAX_GROUP_BY_CLAUSE = "GROUP BY EFF_START_DATE, POLICY, COLLECTN_DAY, BANK_DETAIL_UID, STATUS, LAST_PAYMENT_UID, NEXT_PREM_DUE_DATE, NEXT_PAYT_DUE_DATE, PREM_FREQUENCY ";

	public static final String PREMIUM_COMPONENT_SELECT_COUNT_CLAUSE = "SELECT DISTINCT(COUNT(*) OVER ()) ";
	public static final String PREMIUM_COMPONENT_SELECT_CLAUSE = "SELECT SUM (PREM_AMOUNT) AS PREM_SUM, POLICY, EFF_START_DATE, COLLECTN_DAY, BANK_DETAIL_UID, STATUS, LAST_PAYMENT_UID, NEXT_PREM_DUE_DATE, NEXT_PAYT_DUE_DATE, PREM_FREQUENCY ";
	public static final String PREMIUM_COMPONENT_FROM_CLAUSE = "FROM PHOENIX_PREMIUM.PREMIUM_COMPONENT ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_WHERE = "WHERE LAST_PAYMENT_UID IS NOT NULL";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_RANGE_MIN = " AND (LAST_PAYMENT_UID >= ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_RANGE_MAX = " AND LAST_PAYMENT_UID <= ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_PART1 = ") AND (NEXT_PREM_DUE_DATE >= ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_PART2 = " AND NEXT_PREM_DUE_DATE <= ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_PART3 = ") AND (NEXT_PREM_DUE_DATE >= EFF_START_DATE AND NEXT_PREM_DUE_DATE <= EFF_END_DATE)";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_PART4 = " AND (STATUS IN ('01', '04', '05')) ";
	public static final String PREMIUM_COMPONENT_WHERE_CLAUSE_PART5 = " AND POLICY IS NOT NULL ";
	public static final String PREMIUM_COMPONENT_GROUP_BY_CLAUSE = "GROUP BY EFF_START_DATE, POLICY, COLLECTN_DAY, BANK_DETAIL_UID, STATUS, LAST_PAYMENT_UID, NEXT_PREM_DUE_DATE, NEXT_PAYT_DUE_DATE, PREM_FREQUENCY ";
	public static final String PREMIUM_COMPONENT_HAVING_CLAUSE_PART1 = "HAVING (LAST_PAYMENT_UID >= ";
	public static final String PREMIUM_COMPONENT_HAVING_CLAUSE_PART2 = " AND LAST_PAYMENT_UID <= ";
	public static final String PREMIUM_COMPONENT_HAVING_CLAUSE_PART3 = ")";
	public static final String PREMIUM_COMPONENT_ORDER_BY_CLAUSE = "ORDER BY LAST_PAYMENT_UID DESC";
//	public static final String PREMIUM_COMPONENT_HAVING_BETWEEN_CLAUSE = "HAVING LAST_PAYMENT_UID BETWEEN ";

	public static final String PAYMENT_DETAIL_INSERT_QUERY = "INSERT INTO PHOENIX_PAYMENT.PAYMENT_DETAIL (STATUS, POLICY, BANK_DETAIL_UID, CRTN_TMSTMP, PAYMENT_AMOUNT, ORIG_COLLECTN_DATE, CURRENCY, BACS_CODE, PAYMENT_REF, ORIG_PAYT_SOURCE, PREM_DUE_DATE, PREM_PAYMENT_DATE, COMM_PROCESSED_IND) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static final String PREMIUM_COMPONENT_UPDATE_QUERY = "UPDATE PHOENIX_PREMIUM.PREMIUM_COMPONENT SET NEXT_PREM_DUE_DATE = ?, NEXT_PAYT_DUE_DATE = ?, LAST_PAYMENT_UID = ? WHERE LAST_PAYMENT_UID = ? AND STATUS = ?";

	public static final String PAYMENT_DETAIL_SELECT_QUERY_TO_VERIFY_EXISTING_RECORD = "SELECT * FROM PHOENIX_PAYMENT.PAYMENT_DETAIL where PAYMENT_DETAIL_UID = ";

	public static final String DIARY_EVENT_INSERT_QUERY = "INSERT INTO PHOENIX_DIARY.DIARY_EVENT (POLICY, DIARY_TYPE, DIARY_TIMESTAMP, CREATE_TIMESTAMP, DIARY_SOURCE, DIARY_DATA, STATUS) values(?,?,?,?,?,?,?)";

	public static final String PAYMENT_DETAIL_ARRAER_SUM_PAYMENT_AMOUNT = "SELECT SUM(PAYMENT_AMOUNT) as PAYMENT_AMOUNT FROM PHOENIX_PAYMENT.PAYMENT_DETAIL WHERE POLICY = ? AND STATUS = ?";

}